# Generated by Django 2.0 on 2018-10-21 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='upload',
        ),
    ]
