# Generated by Django 2.0 on 2018-10-22 00:13

from django.db import migrations, models
import videokit.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_remove_video_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=videokit.models.VideoField(blank=True, duration_field='video_duration', height_field='video_height', mimetype_field='video_mimetype', rotation_field='video_rotation', thumbnail_field='video_thumbnail', upload_to='uploads/', width_field='video_width'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_mimetype',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_mp4',
            field=videokit.models.VideoSpecField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='video',
            name='video_ogg',
            field=videokit.models.VideoSpecField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='video',
            name='video_rotation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='video',
            name='video_webm',
            field=videokit.models.VideoSpecField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='video',
            name='video_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
