# Generated by Django 2.0 on 2018-10-25 21:23

from django.db import migrations
import videokit.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20181022_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_height',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_rotation',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_width',
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=videokit.models.VideoField(blank=True, duration_field='video_duration', mimetype_field='video_mimetype', thumbnail_field='video_thumbnail', upload_to='uploads/'),
        ),
    ]
